"""Thresholds centralizados para SignalIQ."""

# NDI Thresholds
NDI_OVERHEATING = 1.5
NDI_WATCHING = 0.7
NDI_ALIGNED = 0.3

# Confidence
CONFIDENCE_BASE = 70
CONFIDENCE_MULTIPLIER = 15

# Price
PRICE_CHANGE_THRESHOLD = 0.02
MIN_PRICE_HISTORY_DAYS = 6

# Rate Limits
RATE_LIMIT_DEFAULT = "200 per day"
RATE_LIMIT_HOUR = "50 per hour"
RATE_LIMIT_PRICES = "10 per minute"
RATE_LIMIT_CLASSIFY = "30 per minute"
RATE_LIMIT_ANALYZE = "10 per minute"

# Cache
CACHE_TTL_SECONDS = 300
