[mypy]
explicit_package_bases = True
namespace_packages = True

[mypy-app.*]
ignore_missing_imports = True

[mypy-layers.*]
ignore_missing_imports = True

[mypy-ingestion.*]
ignore_missing_imports = True
