services:
  - type: web
    name: signaliq-api
    runtime: python
    repo: https://github.com/danacioDS/SignalIQ
    branch: main
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: PORT
        value: 10000
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GLM_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
