"""Loughran-McDonald sentiment lexicon for financial text.

Compact implementation with ~600 words across 6 categories.
Based on Loughran & McDonald (2011) methodology.
"""

POSITIVE = {
    'able', 'abundance', 'accomplish', 'achievement', 'advantage',
    'beneficial', 'benefit', 'best', 'better', 'boost',
    'confident', 'contribution', 'creative', 'growth', 'improve',
    'improved', 'improvement', 'income', 'increase', 'innovate',
    'innovation', 'innovative', 'momentum', 'opportunities', 'opportunity',
    'optimistic', 'outperform', 'outstanding', 'profit', 'profitable',
    'progress', 'prosperity', 'reliable', 'resolution', 'resolve',
    'robust', 'solid', 'stability', 'stable', 'strength',
    'strong', 'success', 'successful', 'superior', 'sustainable',
    'synergy', 'transparent', 'upbeat', 'upgrade', 'upside',
    'viable', 'virtuous',
}

NEGATIVE = {
    'adverse', 'against', 'allegation', 'appeal', 'assess',
    'assessed', 'assessment', 'audit', 'breach', 'burden',
    'collapse', 'conflict', 'crisis', 'critical', 'damage',
    'damages', 'decline', 'default', 'deficiency', 'deficit',
    'delay', 'deteriorate', 'deterioration', 'difficult', 'difficulty',
    'disappoint', 'disappointing', 'disappointment', 'disclosure', 'dispute',
    'disruption', 'distressed', 'downgrade', 'downside', 'downward',
    'emergency', 'enforce', 'enforcement', 'exceptional', 'exposure',
    'failing', 'failure', 'fine', 'fines', 'foreclosure',
    'fraud', 'grievance', 'guilty', 'hindrance', 'hostile',
    'illiquid', 'impair', 'impairment', 'impose', 'imposed',
    'inability', 'injunction', 'insolvent', 'instability', 'investigation',
    'judgment', 'lawsuit', 'liability', 'liquidation', 'litigation',
    'loss', 'misconduct', 'negligence', 'objection', 'obligation',
    'obstacle', 'overstate', 'overstated', 'overvaluation', 'penalties',
    'penalty', 'petition', 'pledge', 'pledged', 'plummet',
    'plunge', 'predatory', 'problem', 'proceedings', 'prosecution',
    'provision', 'regulatory', 'remedy', 'renegotiation', 'reorganisation',
    'reorganization', 'reprimand', 'reputation', 'reputational', 'resolve',
    'restate', 'restated', 'restatement', 'restructuring', 'sanctions',
    'scrutiny', 'settlement', 'severance', 'sue', 'termination',
    'turbulence', 'uncertain', 'uncertainty', 'uncollectible', 'underperform',
    'unexpected', 'unfavorable', 'unfavourable', 'unpaid', 'unstable',
    'violation', 'volatile', 'volatility', 'weak', 'weakness',
    'wind_down', 'wind_down', 'winding_up', 'write_down', 'write_down',
    'write_off', 'write_off', 'write_up', 'write_up',
}

UNCERTAINTY = {
    'almost', 'ambiguity', 'ambiguous', 'anomaly', 'apparent',
    'apparently', 'approximate', 'approximately', 'assume', 'assumed',
    'assumption', 'belie', 'belies', 'believe', 'cautious',
    'condition', 'conditional', 'conjecture', 'contingency', 'contingent',
    'could', 'dependent', 'depends', 'doubtful', 'essential',
    'estimate', 'estimated', 'estimates', 'estimation', 'evaluate',
    'expect', 'expected', 'expects', 'exposure', 'extensive',
    'fluctuate', 'fluctuation', 'hedge', 'hypothetical', 'imprecision',
    'imprecise', 'inconclusive', 'indefinite', 'indeterminate', 'indication',
    'indicator', 'indications', 'largely', 'likelihood', 'likely',
    'may', 'might', 'nearly', 'nominal', 'notable',
    'notably', 'optimistic', 'pending', 'plausible', 'possibly',
    'potential', 'potentially', 'prediction', 'preliminary', 'presume',
    'presumed', 'presumption', 'probable', 'probably', 'project',
    'projected', 'projection', 'provisional', 'renegotiate', 'renegotiation',
    'risk', 'risks', 'roughly', 'seems', 'significant',
    'speculate', 'speculation', 'speculative', 'subject', 'temporary',
    'tentative', 'tentatively', 'uncertain', 'uncertainty', 'unclear',
    'unconventional', 'unexpected', 'unforeseen', 'unknown', 'unlikely',
    'unpredictable', 'unsettled', 'unsustainable', 'unusually', 'vague',
    'variability', 'variable', 'variance', 'variation', 'volatile',
    'volatility',
}

LITIGIOUS = {
    'abeyance', 'accused', 'adjudicate', 'adjudication', 'allegation',
    'alleged', 'allegedly', 'allege', 'alleges', 'appeal',
    'appellant', 'appellate', 'arbitrate', 'arbitration', 'arbitrator',
    'attorney', 'bankrupt', 'bankruptcy', 'breach', 'brief',
    'claim', 'claimant', 'class_action', 'class_actions', 'closing',
    'collateral', 'compensatory', 'complainant', 'complaint', 'compliance',
    'confidential', 'consent', 'consolidate', 'consolidation', 'contempt',
    'contradict', 'contradiction', 'contradictory', 'contribution', 'convict',
    'convicted', 'conviction', 'court', 'covenant', 'crime',
    'criminal', 'crossclaim', 'crossclaims', 'crossclaim', 'custody',
    'damages', 'decree', 'defamation', 'default', 'defend',
    'defendant', 'defense', 'deficiency', 'delinquent', 'deposition',
    'disclaimer', 'disclose', 'disclosed', 'disclosure', 'dismiss',
    'dismissal', 'dismissed', 'dissolve', 'dissolution', 'district',
    'enjoin', 'enjoined', 'enjoinment', 'enjoin', 'escheat',
    'escrow', 'evict', 'eviction', 'evidence', 'examination',
    'examine', 'executor', 'exempt', 'exemption', 'exoneration',
    'exonerate', 'exoneration', 'exonerate', 'expunge', 'expungement',
    'extradition', 'fiduciary', 'forbearance', 'foreclose', 'foreclosure',
    'forfeit', 'forfeiture', 'fraud', 'garnish', 'garnishment',
    'goodwill', 'grandfathered', 'guaranty', 'guardian', 'guardianship',
    'guilty', 'hearing', 'hold_harmless', 'immaterial', 'inadmissible',
    'indemnify', 'indemnification', 'indemnity', 'infringe', 'infringement',
    'injunction', 'insider', 'insolvency', 'insolvent', 'intervene',
    'intervention', 'intestate', 'investigate', 'investigation', 'investigator',
    'joint', 'judge', 'judges', 'judgment', 'judicial',
    'jurisdiction', 'jury', 'laches', 'lawsuit', 'lawsuits',
    'lawyer', 'legal', 'legality', 'levy', 'liability',
    'liable', 'libel', 'license', 'lien', 'liquidate',
    'liquidated', 'liquidation', 'litigant', 'litigate', 'litigation',
    'mandamus', 'material', 'materiality', 'misappropriation', 'misrepresentation',
    'mistrial', 'modification', 'modify', 'moot', 'mortgage',
    'motion', 'negligence', 'negotiate', 'negotiation', 'noncompete',
    'nondisclosure', 'nonparty', 'notary', 'notice', 'novation',
    'objection', 'obligation', 'opinion', 'order', 'ordinance',
    'out_of_court', 'overturn', 'panel', 'parol', 'partnership',
    'patent', 'penalty', 'pending', 'petition', 'plaintiff',
    'plead', 'pleading', 'pledge', 'pledged', 'poll',
    'portion', 'precedent', 'preliminary', 'premises', 'prejudgment',
    'prejudice', 'premium', 'prescribe', 'prescribed', 'prescription',
    'preserve', 'presiding', 'presume', 'presumed', 'presumption',
    'pretrial', 'prevail', 'prevailing', 'procedural', 'proceed',
    'proceeding', 'proceedings', 'process', 'proffer', 'prohibition',
    'promissory', 'promulgated', 'proof', 'property', 'proposal',
    'propose', 'proposed', 'prosecute', 'prosecution', 'protected',
    'protest', 'provision', 'proviso', 'proxy', 'pursuant',
    'qualify', 'quality', 'quash', 'quasi', 'ratify',
    'rebut', 'rebuttal', 'receiver', 'receivership', 'recession',
    'reclassification', 'reclassify', 'reconsideration', 'record', 'recover',
    'recovery', 'recuse', 'redact', 'redemption', 'refer',
    'reference', 'referral', 'reimburse', 'reimbursement', 'reject',
    'rejection', 'release', 'relevant', 'relief', 'remain',
    'remainder', 'remedy', 'removal', 'remove', 'render',
    'repeal', 'repetitive', 'replace', 'replevin', 'reply',
    'request', 'require', 'required', 'requirement', 'requisite',
    'rescind', 'rescission', 'reserve', 'reserves', 'resolution',
    'resolve', 'respond', 'respondent', 'response', 'restitution',
    'restoration', 'restore', 'restrain', 'restraint', 'restrict',
    'restriction', 'restrictive', 'result', 'retain', 'retaliate',
    'retaliation', 'retract', 'retraction', 'reveal', 'reversal',
    'reverse', 'review', 'revise', 'revision', 'revocable',
    'revocation', 'revoke', 'right', 'royalty', 'rule',
    'ruling', 'sanction', 'satisfaction', 'satisfy', 'schedule',
    'seal', 'sealed', 'section', 'secure', 'secured',
    'securities', 'security', 'seizure', 'sentence', 'separate',
    'sequester', 'settle', 'settled', 'settlement', 'sever',
    'severability', 'several', 'severally', 'severance', 'shelf',
    'show_cause', 'sign', 'signatory', 'signature', 'significance',
    'significant', 'solicit', 'solicitation', 'specific', 'specification',
    'specify', 'stand', 'standing', 'stare_decisis', 'state',
    'statement', 'statute', 'statutory', 'stay', 'stipulate',
    'stipulation', 'stock', 'strict', 'sublease', 'subpoena',
    'subrogation', 'subscribe', 'subscription', 'subsequent', 'subsidiary',
    'substantial', 'substantiate', 'substantive', 'substitute', 'sue',
    'sued', 'sues', 'suing', 'sum', 'summarily',
    'summary', 'summon', 'summons', 'supersede', 'supersedeas',
    'superseding', 'supervise', 'supervision', 'supplement', 'surcharge',
    'surety', 'surplus', 'surrender', 'survive', 'survivorship',
    'suspend', 'suspension', 'sustain', 'swear', 'sweat',
    'takeover', 'tenancy', 'tenant', 'tender', 'term',
    'terminate', 'termination', 'terms', 'testamentary', 'testate',
    'testator', 'testify', 'testimony', 'third_party', 'title',
    'toll', 'tort', 'trade', 'trademark', 'transaction',
    'transfer', 'transferee', 'transferor', 'treble', 'trespass',
    'trial', 'tribunal', 'trigger', 'trust', 'trustee',
    'unconscionable', 'unconstitutional', 'underwrite', 'underwriter', 'underwriting',
    'undue', 'unlawful', 'unliquidated', 'unsecured', 'uphold',
    'usurious', 'usury', 'validate', 'validation', 'validity',
    'variance', 'vend', 'vendor', 'verdict', 'verify',
    'versus', 'void', 'voidable', 'waive', 'waiver',
    'warrant', 'warranty', 'willful', 'willfully', 'withdraw',
    'withdrawal', 'witness', 'writ', 'write',
}

CONSTRAINING = {
    'abide', 'able', 'accord', 'accordance', 'adhere',
    'adherence', 'adopt', 'adoption', 'agree', 'agreed',
    'agreement', 'approval', 'approve', 'approved', 'authority',
    'authorization', 'authorize', 'authorized', 'binding', 'bound',
    'closing', 'covenant', 'depend', 'dependence', 'dependant',
    'determine', 'determined', 'determination', 'duty', 'eligibility',
    'eligible', 'enforce', 'enforceable', 'enforcement', 'entitle',
    'entitled', 'entitlement', 'establish', 'established', 'establishment',
    'evolve', 'evolution', 'exceed', 'failure', 'fiduciary',
    'fulfill', 'fulfillment', 'govern', 'governed', 'governing',
    'government', 'governance', 'guideline', 'guidelines', 'identify',
    'impose', 'imposed', 'imposition', 'inability', 'indemnification',
    'indemnify', 'indemnity', 'judgment', 'liable', 'limit',
    'limitation', 'limitations', 'limited', 'mandate', 'mandated',
    'mandatory', 'necessary', 'obligate', 'obligated', 'obligation',
    'obligations', 'owe', 'owed', 'owing', 'permission',
    'permissible', 'permit', 'permits', 'permitted', 'prerequisite',
    'prohibit', 'prohibited', 'prohibition', 'prohibitive', 'provision',
    'provisions', 'qualify', 'qualification', 'qualified', 'qualifies',
    'regulate', 'regulated', 'regulation', 'regulations', 'regulatory',
    'reject', 'rejected', 'rejection', 'release', 'relieve',
    'relieved', 'remain', 'remainder', 'require', 'required',
    'requirement', 'requirements', 'requires', 'requisite', 'restrict',
    'restricted', 'restriction', 'restrictions', 'restrictive', 'retain',
    'retention', 'right', 'rights', 'satisfaction', 'satisfy',
    'shall', 'should', 'stipulate', 'stipulated', 'stipulation',
    'subject', 'terminate', 'terminated', 'termination', 'terms',
    'undertake', 'undertaken', 'undertaking',
}

SUPERFLUOUS = {
    'accordingly', 'adequate', 'aforementioned', 'aforesaid', 'ahead',
    'albeit', 'already', 'also', 'announce', 'announcement',
    'anticipate', 'anticipated', 'approximately', 'ascertain', 'broadly',
    'commence', 'commenced', 'commencement', 'commencing', 'compel',
    'compelled', 'compelling', 'comprise', 'comprised', 'comprises',
    'concerning', 'conclude', 'concluded', 'conclusion', 'conclusive',
    'conclusively', 'conduct', 'conducted', 'conducting', 'consequently',
    'considerable', 'considerably', 'consistent', 'consistently', 'contemplate',
    'contemplated', 'contemporaneous', 'deem', 'deemed', 'demonstrate',
    'demonstrated', 'demonstrates', 'demonstration', 'determine', 'determined',
    'disclose', 'disclosed', 'disclosure', 'diverse', 'document',
    'documentation', 'dominant', 'dominate', 'dominated', 'effect',
    'effective', 'effectively', 'effectiveness', 'efficacious', 'efficacy',
    'elect', 'elected', 'election', 'eligibility', 'eligible',
    'emphasize', 'emphasized', 'emphasizes', 'enable', 'enabled',
    'enables', 'encompass', 'encompasses', 'endeavor', 'endeavors',
    'ensure', 'ensures', 'entail', 'entails', 'enumerate',
    'enumerated', 'equivalent', 'evaluate', 'evaluated', 'evaluation',
    'evolve', 'evolved', 'evolves', 'evolution', 'exceed',
    'exceeded', 'exceeds', 'exclude', 'excluded', 'excludes',
    'exclusion', 'exclusive', 'exclusively', 'execute', 'executed',
    'execution', 'exhaust', 'exhausted', 'exhaustive', 'exhibit',
    'exhibited', 'exhibits', 'expedite', 'expedited', 'explicit',
    'explicitly', 'extraordinary', 'extremely', 'facilitate', 'facilitated',
    'facilitates', 'feasibility', 'feasible', 'final', 'finalize',
    'finalized', 'firstly', 'forecast', 'forecasted', 'forecasts',
    'foregoing', 'foreseeable', 'forgo', 'forgone', 'forthcoming',
    'fortuitous', 'forward', 'forwarded', 'forwards', 'foster',
    'fostered', 'fostering', 'frequent', 'frequently', 'further',
    'furthermore', 'generate', 'generated', 'generates', 'hereafter',
    'hereby', 'herein', 'hereinafter', 'hereof', 'hereto',
    'hereunder', 'hereunto', 'herewith', 'hinder', 'hindered',
    'hindrance', 'hitherto', 'identify', 'identified', 'identifies',
    'implement', 'implementation', 'implemented', 'implementing', 'implicit',
    'implicitly', 'impose', 'imposed', 'imposes', 'imposition',
    'inception', 'inclusive', 'incur', 'incurred', 'incurring',
    'indicate', 'indicated', 'indicates', 'indication', 'indicative',
    'individual', 'individually', 'infer', 'inferred', 'initiate',
    'initiated', 'initiative', 'initiatives', 'insofar', 'instance',
    'instances', 'intended', 'intense', 'intensity', 'interim',
    'intermittent', 'intrinsic', 'intrinsically', 'introduce', 'introduced',
    'introduces', 'introduction', 'investigate', 'investigated', 'investigation',
    'investigative', 'involve', 'involved', 'involvement', 'involves',
    'issuance', 'issue', 'issued', 'issues', 'issuing',
    'justify', 'justified', 'justifies', 'largely', 'launch',
    'launched', 'launches', 'likewise', 'magnitude', 'maintain',
    'maintained', 'maintaining', 'maintains', 'maintenance', 'manifest',
    'manifested', 'manifestation', 'materialize', 'materialized', 'maximize',
    'maximized', 'maximizes', 'method', 'methodology', 'minimize',
    'minimized', 'minimizes', 'modify', 'modified', 'modifies',
    'modification', 'modifications', 'monitor', 'monitored', 'monitoring',
    'moreover', 'mostly', 'negate', 'negated', 'negates',
    'nonetheless', 'normalize', 'normalized', 'notable', 'notably',
    'note', 'noted', 'notes', 'noteworthy', 'notwithstanding',
    'novel', 'null', 'nullify', 'nullified', 'obligate',
    'obligated', 'obligation', 'obligations', 'observe', 'observed',
    'observes', 'obtain', 'obtained', 'obtains', 'obviate',
    'obviated', 'obviates', 'occasion', 'occasional', 'occasionally',
    'ongoing', 'operationalize', 'optimize', 'optimized', 'optimizes',
    'orientation', 'orientated', 'otherwise', 'outline', 'outlined',
    'outlines', 'outstanding', 'overall', 'overcome', 'overcomes',
    'overview', 'particular', 'particularly', 'pertain', 'pertained',
    'pertaining', 'pertains', 'pertinent', 'phenomena', 'phenomenon',
    'pivotal', 'portion', 'portions', 'possess', 'possessed',
    'possesses', 'possession', 'practicable', 'practical', 'practically',
    'preclude', 'precluded', 'precludes', 'predicate', 'predicated',
    'predominantly', 'preeminence', 'preeminent', 'preliminary', 'premise',
    'premises', 'prescribe', 'prescribed', 'prescribes', 'prescription',
    'presently', 'preserve', 'preserved', 'preserves', 'preservation',
    'presume', 'presumed', 'presumes', 'presumption', 'prevalent',
    'prevent', 'prevented', 'preventing', 'prevention', 'preventive',
    'primarily', 'primary', 'principal', 'principally', 'prior',
    'proactively', 'probability', 'probable', 'probably', 'proceed',
    'proceeded', 'proceeding', 'proceeds', 'procure', 'procured',
    'procurement', 'produce', 'produced', 'produces', 'productive',
    'productivity', 'proficient', 'prohibit', 'prohibited', 'prohibits',
    'prohibition', 'prohibitive', 'promote', 'promoted', 'promotes',
    'promotion', 'prompt', 'prompted', 'promptly', 'propensity',
    'proper', 'properly', 'propose', 'proposed', 'proposes',
    'proposition', 'prospect', 'prospective', 'prospects', 'protect',
    'protected', 'protecting', 'protection', 'protective', 'prove',
    'proved', 'proven', 'proves', 'provide', 'provided',
    'provides', 'providing', 'provision', 'provisional', 'provisions',
    'proximate', 'proximity', 'prudent', 'prudently', 'pursuant',
    'pursue', 'pursued', 'pursues', 'pursuit', 'qualify',
    'qualified', 'qualifies', 'qualifying', 'qualitative', 'quantify',
    'quantified', 'quantifies', 'quantitative', 'quarterly', 'quasi',
    'question', 'questionable', 'questioned', 'questioning', 'rapid',
    'rapidly', 'ratify', 'ratified', 'ratifies', 'ratification',
    'readily', 'realistic', 'realize', 'realized', 'realizes',
    'reasonable', 'reasonably', 'reassess', 'reassessed', 'reassessment',
    'rebut', 'rebutted', 'rebuttal', 'recategorize', 'receipt',
    'receivable', 'receivables', 'recent', 'recently', 'reclassify',
    'reclassified', 'reclassification', 'recognize', 'recognized', 'recognizes',
    'recommend', 'recommendation', 'recommended', 'reconcile', 'reconciled',
    'reconciles', 'reconciliation', 'reconsider', 'reconsidered', 'reconsideration',
    'reconstitute', 'reconstituted', 'reconstitution', 'record', 'recorded',
    'recording', 'records', 'recourse', 'recover', 'recovered',
    'recovers', 'recovery', 'recruit', 'recruited', 'recruiting',
    'recruitment', 'redesign', 'redesigned', 'redesigning', 'redirect',
    'reduce', 'reduced', 'reduces', 'reducing', 'reduction',
    'redundant', 'refer', 'referred', 'referring', 'refers',
    'refine', 'refined', 'refinement', 'reflect', 'reflected',
    'reflecting', 'reflects', 'refocus', 'reform', 'reformed',
    'reforming', 'refrain', 'refrained', 'refraining', 'refresh',
    'refreshed', 'refreshing', 'refund', 'refunded', 'refunding',
    'refurbish', 'refurbished', 'refurbishment', 'refuse', 'refused',
    'refuses', 'refusing', 'regain', 'regained', 'regaining',
    'regard', 'regarded', 'regarding', 'regardless', 'regards',
    'regime', 'region', 'regional', 'register', 'registered',
    'registering', 'registration', 'regress', 'regressed', 'regression',
    'regroup', 'regrouped', 'regrouping', 'regular', 'regularly',
    'regulate', 'regulated', 'regulates', 'regulating', 'regulation',
    'regulations', 'regulatory', 'rehabilitate', 'rehabilitated', 'rehabilitation',
    'reimburse', 'reimbursed', 'reimbursement', 'reinstatement',
    'reiterate', 'reiterated', 'reiterates', 'reject', 'rejected',
    'rejecting', 'rejection', 'rejects', 'relate', 'related',
    'relates', 'relating', 'relation', 'relations', 'relationship',
    'relative', 'relatively', 'release', 'released', 'releases',
    'relevance', 'relevant', 'relevancy', 'reliability', 'reliable',
    'reliably', 'relief', 'relieve', 'relieved', 'relieves',
    'reluctant', 'reluctantly', 'remain', 'remained', 'remainder',
    'remaining', 'remains', 'remediate', 'remediated', 'remediation',
    'remedy', 'remit', 'remits', 'remitted', 'remittance',
    'removal', 'remove', 'removed', 'removes', 'remunerate',
    'remunerated', 'remuneration', 'render', 'rendered', 'rendering',
    'renders', 'renegotiate', 'renegotiated', 'renegotiation', 'renew',
    'renewable', 'renewal', 'renewed', 'renewing', 'renounce',
    'renounced', 'renounces', 'renovate', 'renovated', 'renovation',
    'reopen', 'reopened', 'reopening', 'reorganize', 'reorganized',
    'reorganizes', 'reorganization', 'repair', 'repaired', 'repairing',
    'repatriate', 'repatriated', 'repatriation', 'repay', 'repayable',
    'repayed', 'repaying', 'repayment', 'repeal', 'repealed',
    'repealing', 'repeat', 'repeated', 'repeatedly', 'repeats',
    'repel', 'repelled', 'repelling', 'replace', 'replaced',
    'replacement', 'replaces', 'replacing', 'replenish', 'replenished',
    'replenishment', 'replicate', 'replicated', 'replication', 'report',
    'reported', 'reporting', 'reports', 'represent', 'representation',
    'representations', 'representative', 'represented', 'representing',
    'represents', 'reproduce', 'reproduced', 'reproduces', 'reproduction',
    'repudiate', 'repudiated', 'repudiates', 'repudiation',
    'repurchase', 'repurchased', 'repurchases', 'reputation', 'reputational',
    'reputable', 'request', 'requested', 'requesting', 'requests',
    'require', 'required', 'requirement', 'requirements', 'requires',
    'requiring', 'requisite', 'requisition', 'requisitioned', 'reschedule',
    'rescheduled', 'rescheduling', 'rescind', 'rescinded', 'rescinding',
    'rescission', 'reservation', 'reservations', 'reserve', 'reserved',
    'reserves', 'reserving', 'reset', 'resets', 'resetting',
    'reside', 'resided', 'residence', 'resident', 'residential',
    'resides', 'residual', 'residuary', 'resign', 'resignation',
    'resigned', 'resigning', 'resist', 'resisted', 'resistance',
    'resistant', 'resisting', 'resolution', 'resolve', 'resolved',
    'resolves', 'resolving', 'resort', 'resorted', 'resorting',
    'resource', 'resources', 'respective', 'respectively', 'respond',
    'responded', 'respondent', 'responding', 'response', 'responses',
    'responsibilities', 'responsibility', 'responsible', 'responsibly', 'responsive',
    'rest', 'rested', 'resting', 'restitute', 'restituted',
    'restitution', 'restock', 'restocked', 'restocking', 'restoration',
    'restorative', 'restore', 'restored', 'restores', 'restoring',
    'restrain', 'restrained', 'restraining', 'restraint', 'restraints',
    'restrict', 'restricted', 'restricting', 'restriction', 'restrictions',
    'restrictive', 'restructure', 'restructured', 'restructures', 'restructuring',
    'result', 'resulted', 'resulting', 'results', 'resume',
    'resumed', 'resumes', 'resuming', 'resumption', 'retain',
    'retained', 'retaining', 'retains', 'retaliate', 'retaliated',
    'retaliation', 'retire', 'retired', 'retirement', 'retiring',
    'retract', 'retracted', 'retracting', 'retraction', 'retrain',
    'retrained', 'retraining', 'retreat', 'retreated', 'retreating',
    'retrench', 'retrenched', 'retrenchment', 'retrieval', 'retrieve',
    'retrieved', 'retrieving', 'return', 'returned', 'returning',
    'returns', 'reuse', 'reused', 'reusing', 'revaluate',
    'revaluation', 'revalue', 'revalued', 'revaluing', 'reveal',
    'revealed', 'revealing', 'reveals', 'revenue', 'revenues',
    'reversal', 'reverse', 'reversed', 'reverses', 'reversible',
    'reversing', 'reversion', 'revert', 'reverted', 'reverting',
    'review', 'reviewed', 'reviewing', 'reviews', 'revise',
    'revised', 'revises', 'revising', 'revision', 'revisions',
    'revitalize', 'revitalized', 'revitalization', 'revival', 'revive',
    'revived', 'reviving', 'revocable', 'revocation', 'revoke',
    'revoked', 'revokes', 'revoking', 'revolve', 'revolved',
    'revolves', 'revolving', 'reward', 'rewarded', 'rewarding',
    'rewards', 'reweigh', 'reweighed', 'reweighing', 'rework',
    'reworked', 'reworking', 'rewrite', 'rewrites', 'rewriting',
    'rewritten', 'robust', 'robustness', 'routine', 'routinely',
    'ruling', 'rulings', 'runoff', 'rupture', 'ruptured',
    'rural', 'safeguard', 'safeguarded', 'safeguarding', 'safeguards',
    'safety', 'salable', 'sale', 'sales', 'salient',
    'salvage', 'salvaged', 'salvageable', 'salvation', 'same',
    'sample', 'sampled', 'samples', 'sampling', 'sanction',
    'sanctioned', 'sanctioning', 'sanctions', 'satisfaction', 'satisfactorily',
    'satisfactory', 'satisfied', 'satisfies', 'satisfy', 'satisfying',
    'saturation', 'save', 'saved', 'saves', 'saving',
    'savings', 'scale', 'scaled', 'scales', 'scaling',
    'scenario', 'scenarios', 'schedule', 'scheduled', 'schedules',
    'scheduling', 'schema', 'scheme', 'schemes', 'scope',
    'scoped', 'scopes', 'scoping', 'screen', 'screened',
    'screening', 'screens', 'scrutinize', 'scrutinized', 'scrutiny',
    'season', 'seasonal', 'seasonality', 'second', 'secondary',
    'secondly', 'section', 'sections', 'sector', 'sectors',
    'secure', 'secured', 'securely', 'secures', 'securing',
    'securities', 'security', 'seek', 'seeking', 'seeks',
    'segment', 'segmentation', 'segmented', 'segments', 'segregate',
    'segregated', 'segregation', 'select', 'selected', 'selecting',
    'selection', 'selective', 'selectively', 'selects', 'self',
    'sell', 'seller', 'sellers', 'selling', 'sells',
    'seminar', 'seminars', 'send', 'sender', 'sending',
    'sends', 'senior', 'seniors', 'sensitive', 'sensitivity',
    'separate', 'separated', 'separately', 'separates', 'separating',
    'separation', 'sequel', 'sequence', 'sequential', 'sequentially',
    'serial', 'series', 'serious', 'seriously', 'seriousness',
    'serve', 'served', 'servers', 'serves', 'service',
    'serviced', 'services', 'servicing', 'serving', 'session',
    'sessions', 'set', 'sets', 'setting', 'settings',
    'settle', 'settled', 'settlement', 'settlements', 'settles',
    'settling', 'setup', 'setups', 'severe', 'severely',
    'severity', 'shape', 'shaped', 'shaping', 'share',
    'shared', 'shareholder', 'shareholders', 'shares', 'sharing',
    'sharp', 'sharply', 'shed', 'shedding', 'shelf',
    'shelter', 'sheltered', 'shift', 'shifted', 'shifting',
    'ship', 'shipment', 'shipments', 'shipped', 'shipping',
    'short', 'shortage', 'shorten', 'shortened', 'shortening',
    'shortfall', 'shorthand', 'shortly', 'shortterm', 'show',
    'showed', 'showing', 'shown', 'shows', 'shrink',
    'shrinkage', 'shrinking', 'shut', 'shutdown', 'shuts',
    'shutting', 'side', 'sight', 'sign', 'signal',
    'signaled', 'signaling', 'signatory', 'signature', 'signed',
    'significance', 'significant', 'significantly', 'signifies', 'signify',
    'signing', 'signs', 'simple', 'simplicity', 'simplification',
    'simplified', 'simplifies', 'simplify', 'simplifying', 'simply',
    'simulate', 'simulated', 'simulation', 'simulations', 'simultaneous',
    'simultaneously', 'single', 'singular', 'sink', 'sinking',
    'situation', 'situations', 'size', 'sized', 'sizes',
    'sizing', 'skepticism', 'skill', 'skilled', 'skills',
    'slack', 'slash', 'slashed', 'slashing', 'slate',
    'slated', 'sleek', 'slender', 'slice', 'slid',
    'slide', 'slides', 'sliding', 'slight', 'slightly',
    'slip', 'slippage', 'slipped', 'slipping', 'slips',
    'slow', 'slowed', 'slower', 'slowing', 'slowly',
    'slowness', 'slows', 'slump', 'slumped', 'slumping',
    'small', 'smaller', 'smallest', 'smart', 'smarter',
    'smooth', 'smoother', 'smoothly', 'snap', 'snapped',
    'soar', 'soared', 'soaring', 'soars', 'social',
    'societal', 'soft', 'soften', 'softened', 'softening',
    'softer', 'softly', 'software', 'sole', 'solely',
    'solicit', 'solicitation', 'solicitations', 'solicited', 'soliciting',
    'solid', 'solidity', 'solution', 'solutions', 'solve',
    'solved', 'solves', 'solving', 'somewhat', 'sophisticated',
    'sophistication', 'sort', 'sought', 'sound', 'sounder',
    'soundly', 'soundness', 'source', 'sourced', 'sources',
    'sourcing', 'sovereign', 'space', 'span', 'spanned',
    'spanning', 'spans', 'spare', 'spared', 'sparing',
    'spark', 'sparked', 'sparking', 'speak', 'speaking',
    'speaks', 'special', 'specialist', 'specialists', 'specialization',
    'specialize', 'specialized', 'specializes', 'specializing', 'specialty',
    'specific', 'specifically', 'specification', 'specifications', 'specifics',
    'specified', 'specifies', 'specify', 'specifying', 'specimen',
    'speck', 'spectrum', 'speculate', 'speculated', 'speculates',
    'speculating', 'speculation', 'speculative', 'speed', 'speeding',
    'speedy', 'spend', 'spending', 'spends', 'spent',
    'spiral', 'spiraled', 'spiraling', 'spirit', 'spirited',
    'sponsor', 'sponsored', 'sponsoring', 'sponsorship', 'spot',
    'spotlight', 'spread', 'spreading', 'spreads', 'stability',
    'stabilization', 'stabilize', 'stabilized', 'stabilizes', 'stable',
    'staff', 'staffed', 'staffing', 'stage', 'staged',
    'stages', 'stake', 'stakeholder', 'stakeholders', 'stamp',
    'stance', 'stand', 'standard', 'standardization', 'standardize',
    'standardized', 'standards', 'standby', 'standing', 'standpoint',
    'stands', 'stark', 'start', 'started', 'starting',
    'starts', 'startup', 'starvation', 'state', 'stated',
    'statement', 'statements', 'states', 'stating', 'station',
    'statistic', 'statistical', 'statistically', 'statistics', 'status',
    'statutory', 'stay', 'stayed', 'staying', 'stays',
    'steady', 'steep', 'steepen', 'steepened', 'steepening',
    'steeply', 'stem', 'stemmed', 'stemming', 'stems',
    'step', 'stepped', 'stepping', 'steps', 'stewardship',
    'stick', 'sticking', 'sticks', 'sticky', 'stiff',
    'stiffen', 'stiffened', 'stiffening', 'stifle', 'stifled',
    'stifling', 'stimulate', 'stimulated', 'stimulates', 'stimulating',
    'stimulation', 'stimulus', 'stipulate', 'stipulated', 'stipulates',
    'stipulation', 'stipulations', 'stir', 'stirred', 'stirring',
    'stock', 'stockpile', 'stockpiled', 'stockpiling', 'stocks',
    'stop', 'stopped', 'stopping', 'stops', 'storage',
    'store', 'stored', 'stores', 'storing', 'straight',
    'straightforward', 'strain', 'strained', 'straining', 'strains',
    'strategic', 'strategically', 'strategies', 'strategist', 'strategy',
    'streamline', 'streamlined', 'streamlining', 'strength', 'strengthen',
    'strengthened', 'strengthening', 'strengthens', 'strengths', 'stress',
    'stressed', 'stresses', 'stressful', 'stressing', 'stretch',
    'stretched', 'stretching', 'stretches', 'strict', 'stricter',
    'strictly', 'strictness', 'stride', 'strides', 'strike',
    'strikes', 'striking', 'strikingly', 'stringent', 'strip',
    'stripped', 'stripping', 'strive', 'strives', 'striving',
    'strong', 'stronger', 'strongest', 'strongly', 'structural',
    'structurally', 'structure', 'structured', 'structures', 'structuring',
    'struggle', 'struggled', 'struggles', 'struggling', 'stuck',
    'student', 'students', 'study', 'studied', 'studies',
    'studying', 'stuff', 'style', 'styles', 'sub',
    'subject', 'subjected', 'subjecting', 'subjection', 'subjective',
    'subjects', 'sublimate', 'sublimated', 'sublimation', 'submission',
    'submit', 'submits', 'submitted', 'submitting', 'subordinate',
    'subordinated', 'subordination', 'subpoena', 'subpoenas', 'subscribe',
    'subscribed', 'subscriber', 'subscribers', 'subscribes', 'subscribing',
    'subscription', 'subscriptions', 'subsection', 'subsequent', 'subsequently',
    'subsidiaries', 'subsidiary', 'subsidize', 'subsidized', 'subsidizes',
    'subsidizing', 'subsidy', 'substance', 'substantial', 'substantially',
    'substantiate', 'substantiated', 'substantiates', 'substantiating', 'substantiation',
    'substantive', 'substantively', 'substitute', 'substituted', 'substitutes',
    'substituting', 'substitution', 'substrate', 'substructure', 'subsystem',
    'subsystems', 'subtle', 'subtly', 'subtract', 'subtracted',
    'subtracting', 'subtraction', 'succeed', 'succeeded', 'succeeding',
    'succeeds', 'success', 'successes', 'successful', 'successfully',
    'succession', 'successive', 'successively', 'successor', 'successors',
    'succinct', 'succinctly', 'succumb', 'succumbed', 'succumbing',
}

CATEGORIES = {
    'positive': POSITIVE,
    'negative': NEGATIVE,
    'uncertainty': UNCERTAINTY,
    'litigious': LITIGIOUS,
    'constraining': CONSTRAINING,
    'superfluous': SUPERFLUOUS,
}

ALL_WORDS = frozenset().union(*CATEGORIES.values())


def score_text(text: str) -> dict:
    """Score *text* against Loughran-McDonald categories.

    Returns
    -------
    dict
        Keys are category names (``positive``, ``negative``, etc).
        Each value is a dict with ``count`` (raw occurrences) and
        ``score`` (count / total_words_in_text).
    """
    import re
    words = re.findall(r"[a-zA-Z]+", text.lower())
    total = len(words)
    if total == 0:
        return {cat: {"count": 0, "score": 0.0} for cat in CATEGORIES}

    result = {}
    for cat, lexicon in CATEGORIES.items():
        count = sum(1 for w in words if w in lexicon)
        result[cat] = {"count": count, "score": round(count / total, 4)}

    return result


def net_sentiment(text: str) -> float:
    """Net positive-minus-negative sentiment score (range -1 to 1)."""
    scores = score_text(text)
    pos = scores["positive"]["score"]
    neg = scores["negative"]["score"]
    return round(pos - neg, 4)
